spring:
  datasource:
    password: roommate123
    username: roommate
    url: jdbc:postgresql://localhost:5432/roommate
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

  user:
    name: test
    password: test123
    roles: ADMIN

logging:
  level:
    org:
      springframework:
        security: info

roommate:
    rollen:
      admin: Hungfu123, YungTeto, test

