spring:
  datasource:
    password: roommate123
    username: roommate
    url: jdbc:postgresql://localhost:5432/roommate
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.4dc86ada8cc098dd
            client-secret: 54d17600c05c78e1252a1fec774aa45047d736dc
          google:
            client-id: 984101475640-nonv4lo31flmmg0nk9iejj24v26nqc1l.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    org:
      springframework:
        security: info

roommate:
    rollen:
      admin: Hungfu123, YungTeto

